recipe: default.v1
language: en
pipeline:
- name: SingleStepLLMCommandGenerator
  llm:
    model_group: huggingface_llm # Model group ID

policies:
- name: FlowPolicy
- name: IntentlessPolicy
assistant_id: 20241218-000051-arctic-silo